name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags, e.g., v1.0, v2.1.3

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows, darwin, legacy-linux]
        go-version: ['1.22']  # Change to your desired Go version
        arch: ['amd64', 'arm64']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Dependencies
        run: go mod tidy

      - name: Build Binary
        if: matrix.os != 'legacy-linux'
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -ldflags="-s -w" -o ldap-saml-assertions-${{ matrix.os }}-${{ matrix.arch }} .

      - name: Build legacy linux
        if: matrix.os == 'legacy-linux' && matrix.arch == 'amd64'
        run: |
          docker run --rm -v ${{ github.workspace }}:/go/src/app -w /go/src/app centos:7 \
            /bin/bash -c "
              rm -f /etc/yum.repos.d/CentOS-Base.repo && \
              rm -f /etc/yum.repos.d/CentOS-*.repo && \
              echo "[CentOS-Base]" > /etc/yum.repos.d/CentOS-Base.repo && \
              echo "name=CentOS-Base" >> /etc/yum.repos.d/CentOS-Base.repo && \
              echo "baseurl=http://vault.centos.org/7.9.2009/os/x86_64/" >> /etc/yum.repos.d/CentOS-Base.repo && \
              echo "enabled=1" >> /etc/yum.repos.d/CentOS-Base.repo && \
              echo "gpgcheck=1" >> /etc/yum.repos.d/CentOS-Base.repo && \
              yum clean all && \
              yum update -y && \
              yum install -y epel-release && \
              yum install -y golang gcc && go build -o ldap-saml-assertions-legacy-linux-amd64 ."
          
      - name: Upload Binary
        if: matrix.os != 'legacy-linux' && matrix.arch != 'arm64'
        uses: actions/upload-artifact@v4
        with:
          name: ldap-saml-assertions-${{ matrix.os }}-${{ matrix.arch }}
          path: ldap-saml-assertions-${{ matrix.os }}-${{ matrix.arch }}
          
      - name: Create Release
        if: matrix.os != 'legacy-linux' && matrix.arch != 'arm64'
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ github.ref }}
          files: |
            ldap-saml-assertions-${{ matrix.os }}-${{ matrix.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
