name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags, e.g., v1.0, v2.1.3

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows, darwin, legacy-linux]
        go-version: ['1.22']  # Change to your desired Go version
        arch: ['amd64']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Dependencies
        if: matrix.os != 'legacy-linux'
        run: go mod tidy

      - name: Build Binary
        if: matrix.os != 'legacy-linux'
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -ldflags="-s -w" -o ldap-saml-assertions-${{ matrix.os }}-${{ matrix.arch }} .

      - name: Build legacy linux
        if: matrix.os == 'legacy-linux'
        run: |
          docker run --rm -v ${{ github.workspace }}:/go/src/app -w /go/src/app centos:7 \
            /bin/bash -c "
              rm -f /etc/yum.repos.d/CentOS-Base.repo && \
              rm -f /etc/yum.repos.d/CentOS-*.repo && \
              echo '[base]' > /etc/yum.repos.d/CentOS-Base.repo && \
              echo 'name=CentOS-7 - Base' >> /etc/yum.repos.d/CentOS-Base.repo && \
              echo 'baseurl=http://vault.centos.org/7.9.2009/os/x86_64/' >> /etc/yum.repos.d/CentOS-Base.repo && \
              echo 'gpgcheck=0' >> /etc/yum.repos.d/CentOS-Base.repo && \
              echo '[updates]' >> /etc/yum.repos.d/CentOS-Base.repo && \
              echo 'name=CentOS-7 - Updates' >> /etc/yum.repos.d/CentOS-Base.repo && \
              echo 'baseurl=http://vault.centos.org/7.9.2009/updates/x86_64/' >> /etc/yum.repos.d/CentOS-Base.repo && \
              echo 'gpgcheck=0' >> /etc/yum.repos.d/CentOS-Base.repo && \
              echo '[extras]' >> /etc/yum.repos.d/CentOS-Base.repo && \
              echo 'name=CentOS-7 - Extras' >> /etc/yum.repos.d/CentOS-Base.repo && \
              echo 'baseurl=http://vault.centos.org/7.9.2009/extras/x86_64/' >> /etc/yum.repos.d/CentOS-Base.repo && \
              echo 'gpgcheck=0' >> /etc/yum.repos.d/CentOS-Base.repo && \
              yum clean all && \
              yum update -y && \
              yum install -y wget gcc && \
              wget https://go.dev/dl/go1.22.8.linux-amd64.tar.gz && \
              tar -C /usr/local -xzf go1.22.8.linux-amd64.tar.gz && \
              export PATH=$PATH:/usr/local/go/bin && \
              go mod tidy && \
              go build -ldflags="-s -w" -o ldap-saml-assertions-legacy-linux-amd64 ."
          
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: ldap-saml-assertions-${{ matrix.os }}-${{ matrix.arch }}
          path: ldap-saml-assertions-${{ matrix.os }}-${{ matrix.arch }}
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ github.ref }}
          files: |
            ldap-saml-assertions-${{ matrix.os }}-${{ matrix.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
